/**
 * This file is auto-generated by running 'pnpm build:types'
 * Do not edit this file directly.
 */

export type TokenId = 'aBOBSOLVBTCBBN' | 'aBOBTBTC' | 'aBOBWBTC' | 'ALEX' | 'AVAX' | 'BABY' | 'BERA' | 'BNB' | 'BOB' | 'BTC+' | 'cbBTC' | 'DAI' | 'DLLR' | 'ETH' | 'EURC' | 'FBTC' | 'FRAX' | 'FXS' | 'HybridBTC.pendle' | 'iontBTC' | 'iontWBTC' | 'LBTC' | 'LINK' | 'oUSDT' | 'PAXG' | 'POL' | 'pumpBTC' | 'PYUSD' | 'rETH' | 'S' | 'satUSD' | 'satUSDv2' | 'sbtBTC' | 'sbWBTC' | 'SEI' | 'seSOLVBTCBBN' | 'seTBTC' | 'seUNIBTC' | 'seWBTC' | 'sFRAX' | 'sfrxETH' | 'Solv' | 'SolvBTC' | 'SolvBTC.JUP' | 'SOV' | 'STONE' | 'T' | 'tBTC' | 'thUSD' | 'TLOS' | 'TRB' | 'TRX' | 'UNI' | 'uniBTC' | 'USDC' | 'USDT' | 'USDT0' | 'WBNB' | 'WBTC' | 'WBTCOFT' | 'WETH' | 'wstETH' | 'XAUt' | 'XAUt0' | 'xSolvBTC';
export type NativeTokenId = 'AVAX' | 'BERA' | 'BNB' | 'ETH' | 'POL' | 'S' | 'SEI' | 'TLOS' | 'TRX';

