import fs from 'node:fs';
import path from 'node:path';
import { NON_EVM_CHAIN_NAMES, OUTFILE_TYPES, TOKEN_DIR } from '../config';
import type { TokenData } from '../types';

const tokenlistDirectories = fs.readdirSync(TOKEN_DIR).sort((a, b) => {
  return a.toLowerCase().localeCompare(b.toLowerCase());
});

const tokenlistData = tokenlistDirectories.map<[string, TokenData]>((dir) => {
  const data: TokenData = JSON.parse(
    fs.readFileSync(path.join(TOKEN_DIR, dir, 'data.json'), 'utf8'),
  );

  return [dir, data];
});

const nativeTokenIds = tokenlistData.reduce<string[]>(
  (acc, [tokenId, data]) => {
    if (data.native) {
      acc.push(tokenId);
    }
    return acc;
  },
  [],
);

// Tokens with at least one entry on a non-EVM chain (Solana, Bitcoin
// networks, Tron), and the native subset of those.
const nonEvmTokenIds = tokenlistData.reduce<string[]>(
  (acc, [tokenId, data]) => {
    if (
      Object.keys(data.tokens).some((chain) => NON_EVM_CHAIN_NAMES.has(chain))
    ) {
      acc.push(tokenId);
    }
    return acc;
  },
  [],
);

const nonEvmNativeTokenIds = nonEvmTokenIds.filter((tokenId) =>
  nativeTokenIds.includes(tokenId),
);

function toUnionType(tokenIds: string[]) {
  return tokenIds.map((tokenId) => `'${tokenId}'`).join(' | ') || 'never';
}

const fileDisclaimer = `/**
 * This file is auto-generated by running 'pnpm build:types'
 * Do not edit this file directly.
 */\n\n`;

const content = `export type TokenId = ${toUnionType(tokenlistDirectories)};
export type NativeTokenId = ${toUnionType(nativeTokenIds)};
export type NonEvmTokenId = ${toUnionType(nonEvmTokenIds)};
export type NonEvmNativeTokenId = ${toUnionType(nonEvmNativeTokenIds)};\n`;

fs.writeFileSync(OUTFILE_TYPES, fileDisclaimer + content);
