import fs from 'node:fs';
import path from 'node:path';
import { DATA_DIR, OUTFILE_TYPES } from '../config';
import type { TokenData } from '../types';

const tokenlistDirectories = fs.readdirSync(DATA_DIR).sort((a, b) => {
  return a.toLowerCase().localeCompare(b.toLowerCase());
});

const tokenlistData = tokenlistDirectories.map<[string, TokenData]>((dir) => {
  const data: TokenData = JSON.parse(
    fs.readFileSync(path.join(DATA_DIR, dir, 'data.json'), 'utf8'),
  );

  return [dir, data];
});

const nativeTokenIds = tokenlistData.reduce<string[]>(
  (acc, [tokenId, data]) => {
    if (data.native) {
      acc.push(tokenId);
    }
    return acc;
  },
  [],
);

function toUnionType(tokenIds: string[]) {
  return tokenIds.map((tokenId) => `'${tokenId}'`).join(' | ') || 'never';
}

const fileDisclaimer = `/**
 * This file is auto-generated by running 'pnpm build:types'
 * Do not edit this file directly.
 */\n\n`;

const content = `export type TokenId = ${toUnionType(tokenlistDirectories)};
export type NativeTokenId = ${toUnionType(nativeTokenIds)};\n\n`;

fs.writeFileSync(OUTFILE_TYPES, fileDisclaimer + content);
